_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

_main:
    resource: routing.yml

login:
    pattern: /login
    defaults: { _controller: IpzenAppBundle:Security:login}
    
login_check:
    pattern: /login_check

logout:
    path:    /logout
    defaults: { _controller: IpzenAppBundle:Security:logout}
    
test_security:
    pattern: /secured_area
    defaults: { _controller: IpzenAppBundle:Security:testAuth }

admin:
    pattern: /admin
    defaults: { _controller: IpzenAppBundle:Default:admin }

search_whois: 
    pattern: /whois/search
    defaults: { _controller: IpzenAppBundle:Whois:search}